tencho/tencho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from products.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',index, name='index'),
    path('product_detail/<int:product_id>/', product_detail, name='product_detail'),
    path('catalogue/',include('products.urls', namespace='catalogue')),
    path('about/', about, name='about'),
    path('users/',include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    #api
    path('api/v1/productlist_index/', ProductsAPIViews.as_view()),
    path('api/v1/productlist_index_new/', ProductsAPIViewsNews.as_view()),
    path('product_detail/<int:id>/api/v1/productlist_in_one_category/', ProductsAPIViewsInOneCategory.as_view()),
    path('api/v1/productlist_in_catalogue/', ProductsAPIViewsCataloque.as_view()),
    
] \
+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tencho/users/urls.py
#from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'users'  

urlpatterns = [
    path('cabinet/',views.cabinet, name='cabinet'),
    path('cabinet_no_autorization/',views.cabinet_no_autorization, name='cabinet_no_autorization'),
    path('cabinet/data/',views.data, name='data'),
    path('cabinet/delivery/', views.delivery, name='delivery'),
    path('cabinet/users_cards/',views.users_cards, name='users_cards'),
    path('cabinet/purchases/', views.purchases, name = 'purchases'),
    path('cabinet/favorite/', views.favorite, name='favorite'),
    path('cabinet/notifications',views.notify, name='notify'),
    path('login/', views.login,name='login'),
    path('registation/', views.registration, name='registration'),
    path('logout/', views.logout_view, name='logout'),
]

tencho/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    image = models.ImageField(upload_to='users_avatar/', null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name='Пользователь'
        verbose_name_plural = 'Пользователи'

class Cards(models.Model):
    user = models.ForeignKey(
        User, verbose_name="Пользователь", on_delete=models.CASCADE)
    card_number_hash = models.CharField(max_length=255, unique=True)  # Хеш номера карты
    expiry_date = models.DateField()
    card_type = models.CharField(max_length=20, choices=(
        ('visa', 'Visa'),
        ('mastercard', 'Mastercard'),
        ('mir', 'МИР'),
    ))
    class Meta:
        verbose_name = 'Карта для оплаты'
        verbose_name_plural = 'Карты для оплаты'

tencho/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя' 
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль' 
    }))
    class Meta:# ну м ытут если что указываем с кем мы работаем
        model = User
        fields = ['username', 'password']

class UserProfileForm(UserChangeForm):
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))

    class Meta:
        model = User
        fields = ['last_name', 'first_name', 'image', 'username','email', 'address']


class UserRegistrationForm(UserCreationForm):
    # first_name = forms.CharField(widget=forms.TextInput(attrs={
    #     'placeholder': 'Введите фамилию' 
    # }))
    # last_name = forms.CharField(widget=forms.TextInput(attrs={
    #     'placeholder': 'Введите имя' 
    # }))
    # username = forms.CharField(widget=forms.TextInput(attrs={
    #     'placeholder': 'Введите имя пользователя' 
    # }))
    # email = forms.CharField(widget=forms.EmailInput(attrs={
    #     'placeholder': 'Введите электронную почту' 
    # }))
    # password = forms.CharField(widget=forms.PasswordInput(attrs={
    #     'placeholder': 'Введите пароль' 
    # }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username','email']
    
    # def __init__(self, *args, *kwargs):
    #     super().__init__(*args, *kwargs)
    #     self.helper = FormHelper()
    #     self.helper.layout = Layout(
    #         Field('first_name', css_class='form-control', placeholder='Фамилия'),
    #         Field('last_name', css_class='form-control', placeholder='Имя'),
    #         Field('username', css_class='form-control', placeholder='Имя пользователя'),
    #         Field('email', css_class='form-control', placeholder='Электронная почта'),
    #         Field('password', css_class='form-control', placeholder='Пароль'),
    #         Submit('submit', 'Зарегистрироваться', css_class='btn btn-primary')
    #     )

tencho/users/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from .models import User
from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth import logout

# Create your views here.

def cabinet(request):
    return render(request,'users/cabinet.html')

def cabinet_no_autorization(request):
    return render(request,'users/no_autorization_cabinet.html')

def data(request):
    if request.method == 'POST':
        form = UserProfileForm(instance = request.user,data = request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:data'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance = request.user)
    context = {'form': form}
    return render(request, 'users/tabs_cabinet/data.html', context)

def delivery(request):
    return render(request,'users/tabs_cabinet/delivery.html')

def users_cards(request):
    return render(request,'users/tabs_cabinet/users_cards.html')

def purchases(request):
    '''Покупки'''
    return render(request,'users/tabs_cabinet/purchases.html')

def favorite(request):
    return render(request, 'users/tabs_cabinet/favorite.html')

def notify(request):
    return render(request,'users/tabs_cabinet/notify.html')

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)#заполняем нашими данными форму
        if form.is_valid():#если они прошли проверку
            username = request.POST['username']#забираем наши данные
            password = request.POST['password']
              # Добавить отладку
            #начинаем аутентификацию
            user = auth.authenticate(username=username, password=password)
            if user:
                # Получаем URL из сессии
                auth.login(request, user)
                
                return HttpResponseRedirect(reverse('users:cabinet'))

                # здесь мы проверяем ну то есть если такой пользователь нашелся то происходит авторизация
                
        else:
            print(form.errors)
    else:
        form = UserLoginForm()#это просто получение формы
    context = { 'form' : form}
    return render(request,'users/login.html', context)



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))





def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Поздравляем! Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('users:login'))
        else:
            print(form.errors)
    else:
        form = UserRegistrationForm()
    
    context = {'form': form}
    return render(request, 'users/registration.html', context)

tencho/users/templates/users/cabinet.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/cabinet/cabinet.css' %}">
{% endblock %}
{% block title %}
<title> Tencho - Account</title>
{% endblock %}

{% block content %}
        <div class="cabinet">
            <div class="cabinet-title">
                <p>Личный кабинет</p>
            </div>
            <div class="cards">
                <div class="big-cards">
                <a href="{% url 'users:data' %}" >
                    <div class="card user-info">
                        <div class="top">
                            <img width="80" height="80"
                            src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/Icons/user.png' %} {% endif %}" alt="user"
                            class="img-thumbnail our_image_style">
                            <p class="delivery-counter">{{user.first_name}} {{user.last_name}}</p>
                        </div>
                        <div class="bot data-bot">
                            <div class="data">
                                <p>Логин: {{user.username}}</p>
                                <p>Email: {{user.email}}</p>
                            </div>
                            <a class="logout" href="{% url 'users:logout' %}">
                                <p class="delivery-counter">Выйти</p>
                            </a>
                        </div>
                    </div>
                </a>
                
                    <div class="card delivery-info">
                        <a href="{% url 'users:delivery' %}">
                        <div class="top">
                            <img src="{% static 'img/Icons/cabinetDeliveryIcon.png' %}" alt="user">
                            <p class="delivery-counter">Доставки</p>
                        </div>
                        <div class="bot">
                            <p class="delivery-counter">У вас <span class="hover_marks">нет</span> активных доставок</p>
                        </div>
                    </a>
                    </div>
                
                    <div class="card sales-info">
                        <div class="top">
                            <img src="{% static 'img/Icons/CabinetSalesIcon.png' %}" alt="user">
                            <p style="color: #5F9D9F;">Скидки</p>
                        </div>
                        <div class="bot">
                            <div class="sale-counter">
                                <p style = "color: #5F9D9F;">Персональная скидка —</p>
                                <div class="sale">
                                    <p class="sale-number s1">27%</p>
                                    <p class="sale-number s2">27%</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="small-cards">
                    <a href="{% url 'users:users_cards' %}">
                    <div class="orders">
                        <p class="delivery-counter">Мои карты</p>
                        <p>*4553 VISA</p>
                    </div>
                </a>
                <a href="{% url 'users:purchases' %}">
                    <div class="orders">
                        
                        <p class="delivery-counter">Покупки</p>
                        <p class="delivery-counter">У вас <span class="hover_marks">4</span> покупки</p>
                        
                    </div>
                </a>
                <a href="{% url 'users:favorite' %}">
                    <div class="favourite">
                        <p class="delivery-counter">Избранное</p>
                        <p><span class="hover_marks">15</span> товаров</p>
                    </div>
                </a>
                <a href="{% url 'users:notify' %}">
                    <div class="notifications">
                        <p class="delivery-counter">Уведомления</p>
                        <div class="notifications-block">
                            <img src="{% static 'img/Icons/Bell.png' %}" alt="bell">
                            <p style="color: bfbfbf;"><span class="hover_marks">2</span> новых</p>
                        </div>
                    </div>
                </a>
                </div>
                <div class="thanks">
                    <img src="{% static 'img/cabinet-logo.png' %}" alt="cabinet-logo">
                    <p>Спасибо, что выбираете нас!</p>
                </div>
            </div>
        </div>
        {%endblock%}

        {% block js %}
    <script src="{% static 'js/burger.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    {% endblock %}

tencho/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login/login.css' %}">
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}
{% block title%}
<title> Tencho - LogIn</title>
{% endblock %}

{%block content %}
        <div class="login-form">
            <div class="login-title">
                <p>Авторизация</p>
            </div>
            {% if messages or form.non_field_errors %}
                        <div class="alert
                        {% if messages %} alert-success {% else %} alert_our_color{% endif %}
                         alert-dismissible fade show" role="alert">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}

            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form">
                    <label for="{{form.username.id_for_label}}">Имя пользователя:</label>
                        {{form.username}}
                    <label for="form.password.id_for_label">Пароль:</label>
                        {{form.password}}
                <div class="my_btn">
                    <input type="submit" class="btn a" value = "Войти"> 
                </div>
            
                <div class="underline"></div>
                <a href="{% url 'users:registration'%}">Ещё нет аккаунта? Зарегистрируйтесь!</a>
            </div>
        </form>
        </div>

        {% endblock %}
        {%block js%}
    <script src="{% static 'js/burger.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.js' %}"></script>
        {% endblock%}

tencho/users/templates/users/no_autorization_cabinet.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/cabinet/no_autorization_cabinet.css' %}">
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

{% endblock %}

{% block title %}
<title>Tencho - Cabinet</title>
{% endblock %}

{% block content %}
        <div class="cabinet">
            <div class="cabinet-title">
                <p>Личный кабинет</p>
            </div>
            <div class="alert alert_our_color text-center" role="alert">
                Упс! Вы не авторизованы, пожалуйста, <a href = "{% url 'users:login' %}" class="alert_a">авторизуйтесь</a>
            </div>
            <div class="cards">
                <div class="thanks">
                    <img src="{% static 'img/cabinet-logo.png' %}" alt="cabinet-logo">
                    <p>Спасибо, что выбираете нас!</p>
                </div>
            </div>
        </div>
        {% endblock %}
       {% block js %}
       <script src="/js/burger.js"></script>
    <script src="/js/smooth-scroll.js"></script>
    {%endblock%}

tencho/users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block css%}
<link rel="stylesheet" href="{% static 'css/registration/registration.css' %}">
{% endblock %}

{% block title%}
<title> Tencho - Registartion</title>
{% endblock %}

{% block content %}
        <div class="registration-form">
            <div class="registration-title">
                <p>Регистрация</p>
            </div>
        <form action="{% url 'users:registration'%}" method="post">
            {% csrf_token %}
            <div class="reg-form">
                {{form.as_div}}
                <!--<label for="{{form.first_name.id_for_label}}">Фамилия:</label>
                    {{form.first_name}}
                <label for="{{form.last_name.id_for_label}}">Имя:</label>
                    {{form.last_name}}
                <label for="{{form.username.id_for_label}}">Имя пользователя:</label>
                    {{form.username}}
                <label for="{{form.email.id_for_label}}">Электронная почта:</label>
                    {{form.email}}
                <label for="{{form.password.id_for_label}}">Пароль:</label>
                    {{form.password}}-->
                <div class="btn">
                    <input type="submit" class="btn a" value = "Зарегистрироваться">
                </div>
                
                <div class="redirect">
                    <a href="{% url 'users:login'%}">Уже есть аккаунт? Войдите!</a>
                </div>
            </div>
        </form>
        </div>
        {% endblock%}
        {% block js%}
    <script src="{% static 'js/burger.js'%}"></script>
    <script src="{% static 'js/smooth-scroll.js'%}"></script>
    {% endblock%}