tencho/orders/urls.py
from django.urls import path

from . import views
from .views import basket_add, basket_delete

app_name = 'orders'  

urlpatterns = [
    path('',views.cart, name='order'),
    #path('baskets/add/<int:product_id>/',, name='basket_add'),
    #api
    path('basket/add/',basket_add,name='basket_add'),
    path('basket/delete/',basket_delete,name="basket_delete")
    #path('',views.about, name='about'),
    #path('catalogue/',include('products.urls'), namespace='catalogue')
]

tencho/products/urls.py
#from django.contrib import admin
from django.urls import path

from products import views
from .views import ProductsAPIViewsCataloque
app_name = 'products'  

urlpatterns = [
    path('',views.catalogue, name='catalogue'),
    #path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
    #api
    #пока что наш путь для получения 
    # главное чтобы в пути было api/ дальше версия api api/v1 ну и добавляем немного контекста api/v1/productlist

    #path('',views.about, name='about'),
    #path('catalogue/',include('products.urls'), namespace='catalogue')
]

tencho/tencho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from products.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',index, name='index'),
    path('product_detail/<int:product_id>/', product_detail, name='product_detail'),
    path('catalogue/',include('products.urls', namespace='catalogue')),
    path('about/', about, name='about'),
    path('users/',include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    #api
    path('api/v1/productlist_index/', ProductsAPIViews.as_view()),
    path('api/v1/productlist_index_new/', ProductsAPIViewsNews.as_view()),
    path('product_detail/<int:id>/api/v1/productlist_in_one_category/', ProductsAPIViewsInOneCategory.as_view()),
    path('api/v1/productlist_in_catalogue/', ProductsAPIViewsCataloque.as_view()),
    
] \
+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tencho/users/urls.py
#from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'users'  

urlpatterns = [
    path('cabinet/',views.cabinet, name='cabinet'),
    path('cabinet_no_autorization/',views.cabinet_no_autorization, name='cabinet_no_autorization'),
    path('cabinet/data/',views.data, name='data'),
    path('cabinet/delivery/', views.delivery, name='delivery'),
    path('cabinet/users_cards/',views.users_cards, name='users_cards'),
    path('cabinet/purchases/', views.purchases, name = 'purchases'),
    path('cabinet/favorite/', views.favorite, name='favorite'),
    path('cabinet/notifications',views.notify, name='notify'),
    path('login/', views.login,name='login'),
    path('registation/', views.registration, name='registration'),
    path('logout/', views.logout_view, name='logout'),
]

tencho/products/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class CategoryProducts(models.Model):
    name=models.CharField(max_length=128,unique=True)
    code=models.CharField(max_length=128, default='empty')

    class Meta: 
        verbose_name='Категория'
        verbose_name_plural='Категории'
    
    def __str__(self):
        return self.name
    
class Size(models.Model):
    name=models.CharField(max_length=12)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'
    
class Product(models.Model):
    #ВНИМАНИЕ on_delete указывает, что произойдет, если поле КАТЕГОРИЯ будет удалено
    name=models.CharField(max_length=128)
    cost=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(CategoryProducts,on_delete=models.CASCADE)#тоже будет удален
    description=models.TextField()
    image=models.ImageField(upload_to='products_images/')
    is_active=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True, auto_now=False)
    updated=models.DateTimeField(auto_now_add=False, auto_now=True)

    def get_image_url(self):
           """Возвращает полный URL изображения с учетом MEDIA_URL."""
           if self.image:
               return f"{settings.MEDIA_URL}{self.image.name}"
           return None

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
    
    def __str__(self):
        return '%s %s' % (self.category, self.name)

tencho/products/views.py
from rest_framework import generics
from .models import Product, Size
from orders.models import Basket
from users.models import User
from .serializers import *
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import render, get_object_or_404
import requests

# Create your views here.
#отображение страниц
def index(request):
    response = requests.get('http://127.0.0.1:8001/api/v1/productlist_index/')
    if response.status_code == 200:  # Проверяем, был ли запрос успешным
        popular_products = response.json()  # Получаем данные в формате JSON
    else:
        popular_products = []  # Возвращаем пустой список, если запрос не удался
    
    response = requests.get('http://127.0.0.1:8001/api/v1/productlist_index_new/')
    if response.status_code == 200:  # Проверяем, был ли запрос успешным
        new_products = response.json()  # Получаем данные в формате JSON
    else:
        new_products = []  # Возвращаем пустой список, если запрос не удался
    #popular_products = 'api/v1/productlist_index/'
    context = {
        'sizes': Size.objects.all(),
        'popular_products':popular_products,
        'new_products': new_products
    }
    return render(request,'products/index.html', context)

def catalogue(request):
    response = requests.get('http://127.0.0.1:8001/api/v1/productlist_in_catalogue/')
    if response.status_code == 200:  # Проверяем, был ли запрос успешным
        all_products = response.json()  # Получаем данные в формате JSON
    else:
        all_products = []  # Возвращаем пустой список, если запрос не удался
    
    context = {
        'sizes': Size.objects.all(),
        'all_products': all_products
    }
    return render(request, 'products/catalogue.html', context)


def about(request):
    return render(request,'about.html')

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    similars_products = Product.objects.filter(category=product.category).exclude(pk=product.pk)[:3]  # похожие товары

    context = {
        'sizes': Size.objects.all(),
        'product': product,
        'similars_products': similars_products,
        'counter': 0
    }
    return render(request, 'products/product.html', context)

#Обработчики событий
# def basket_add(request, product_id):
#     if not request.user.is_authenticated:
#         # Сохранение URL в сессии
#         request.session['next_url'] = request.META.get('HTTP_REFERER', '/') 

#         return redirect('users:login')
    

#APIViews
class ProductsAPIViews(APIView):# в общем это то, что мы получаем
    def get(self, request):
        all_products = Product.objects.order_by('created')[:12]
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    
class ProductsAPIViewsInOneCategory(APIView):# в общем это то, что мы получаем
    def get(self, request, id):
        all_products = Product.objects.all()
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    
class ProductsAPIViewsNews(APIView):# в общем это то, что мы получаем
    def get(self, request):
        all_products = Product.objects.order_by('-created')[:6]
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    
class ProductsAPIViewsCataloque(APIView):# в общем это то, что мы получаем
    def get(self, request):
        all_products = Product.objects.all()
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    



# А МОЖНО И ВОТ ТАК

# class ProductsAPIViews(APIView):# он уже говорит какой запрос пришел, а функции мы прописали сами
#     def get(self, request):
#         all_products = Product.objects.all()
#         serialized_products = ProductSerializer(all_products, many=True).data
        
#         response_data = {} 
#         for i, product in enumerate(serialized_products):
#             response_data[str(i + 1)] = product 
        
#         return Response(response_data)
    
#     def post(self, request):
#         serializer  =ProductSerializer(data=request.data)
#         serializer.is_valid(reise_exception=True)
#         serializer.save()
#         return Response({serializer.data})


#МОЖНО ТАК
# class ProductsAPIViews(generics.ListAPIView):# это у нас представление
#     queryset=Product.objects.all()# считываем все
#     serializer_class = ProductSerializer# сериализатор наш

tencho/products/templates/products/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index/adventages.css' %}">
<link rel="stylesheet" href="{% static 'css/index/main-banner.css' %}">
<link rel="stylesheet" href="{% static 'css/index/new.css' %}">
<link rel="stylesheet" href="{% static 'css/index/popular.css' %}">
<link rel="stylesheet" href="{% static 'css/index/second-banner.css' %}">
{%endblock%}
{% block title %}

<title>Tencho</title>

{%endblock%}

{% block content %}

<!--Здесь начинается основная часть-->
        <div class="main-banner" style="background-image: url({% static 'img/banner1.png' %});">
            <div class="offer">
                <p>Фирменные палочки в подарок к каждому заказу!</p>
                <a href="{% url 'catalogue:catalogue'%}">Заказать</a>
            </div>
        </div>
        <div class="adventages">
            <div class="delivery">
                <img src="{% static 'img/Icons/delivery.png' %}" alt="delivery">
                <p>Быстрая доставка</p>
            </div>
            <div class="quality">
                <img src="{% static 'img/Icons/flame.png' %}" alt="quality">
                <p>Высокое качество</p>
            </div>
            <div class="sales">
                <img src="{% static 'img/Icons/sale.png' %}" alt="sales">
                <p>Частые скидки</p>
            </div>
            <div class="return">
                <img src="{% static 'img/Icons/return.png' %}" alt="return">
                <p>Бесплатный возврат</p>
            </div>
        </div>
        <div class="popular">
            <div class="title">Популярные товары</div>
            
            <div class="items">
                {% for product in popular_products %}
                <div class="item">
                    <div class="item-content">
                        <span class="detailed" onclick="modalWindow(this)" data-name="{{product.name}}" data-cost="{{product.cost}}"  data-img="{{product.image}}" data-desc="{{product.description}}" data-category="{{product.category}}">Подробнее</span>
                        <img src="{{product.image}}" alt="{{product.name}}">
                        <div class="underline"></div>
                        <p class="item-title">{{product.name}}</p>
                        <p class="price">Цена: {{product.cost}}₽</p>
                        <a href="/product_detail/{{product.id}}" onclick="buy(this)" data-name="'+data[key].name+'" data-cost="'+data[key].cost+'"  data-img="'+data[key].image+'" data-desc="'+data[key].description+'" data-category="'+data[key].category+'">Купить</a>
                    </div>
                </div>
                {% endfor %}  
                <!--zoom.js применяется внутри createcards.js-->
            </div>
            
        </div>
        
        <a href="{% url 'catalogue:catalogue' %}" class="second-banner-link">
            <div class="second-banner" style = "background-image: url({% static 'img/banner2.png' %});">
                <div class="text">
                    <p>1+1 = 3</p>
                    <p>Закажи 2 соуса и получи третий в подарок</p>
                </div>
            </div>
        </a>
        <div class="new">
            <p class="new-title">Новинки</p>
            <div class="new-items">
                <!--Также тут же начинает работать slider.js-->
                <button class="slider-prev" style="background-image: url({% static 'img/arrow-left.png' %});"></button>
                <div class="slider-container">
                    <div class="slider-track">
                        {% for product in new_products %}
                        <div class="slider-item">
                            
                            <div class="slider-item-content">
                                
                            <span class="detailed" onclick="modalWindow(this)" data-name="{{product.name}}" data-cost="{{product.cost}}"  data-img="{{product.image}}" data-desc="{{product.description}}" data-category="{{product.category}}">Подробнее</span>
                            <img src="{{product.image}}" alt="{{product.name}}">
                            <div class="slider-info">
                            <h1 class="slider-item-title">{{product.name}}</h1>
                            <p class="price">Цена: {{product.cost}} ₽</p>
                            <a class="slider-buy-btn" href="/product_detail/{{product.id}}" onclick="buy(this)" data-name="{{product.name}}" data-cost="{{product.cost}}"  data-img="{{product.image}}" data-desc="{{product.description}}" data-category="{{product.category}}">Купить</a>
                            </div>
                            
                            </div>
                            
                        </div>
                        {% endfor %}
                        
                    </div>
                </div>
                <button class="slider-next" style = "background-image: url({% static 'img/arrow-right.png' %});"></button>
            </div>
        </div>
        {%endblock%}
        <!--Здесь начинается футер-->
        
        {% block footer %}
        <div class="back-btn">
            <a href="#header">
                <img src="{% static 'img/arrow-up5.png' %}" alt="back-scroll">
            </a>
        </div>
        <div class="zoom-modal">
            <div class="modal-content">
                <div class="modal-item">
                    <div class="modal-item-content">
                        <img src="" class="modal-image" alt="tofu">
                    </div>
                </div>
                <div class="about">
                    <h1 class="modal-title"></h1>
                    <p class="modal-price"></p>
                    <p>Размеры:</p>
                    <div class="sizes">
                        {% for size in sizes %}
                        <div>{{size.name}}</div>
                        {% endfor %}
                    </div>
                    <p class="modal-item-about"></p>
                </div>
                <span class="close">X</span>
            </div>
        </div>
        {%endblock%}
    {% block js %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/burger.js' %}"></script>
    <script src="{% static 'js/zoom.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.js' %}"></script>
    <script src="{% static 'js/createcards.js' %}"></script>
    <script src="{% static 'js/scrolltoTop.js' %}"></script>
    <script src="{% static 'js/product.js' %}"></script>
    <script src="{% static 'js/slider.js' %}"></script>
    {%endblock%}

tencho/products/templates/products/product.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/product/product.css' %}">
<link rel="stylesheet" href="{% static 'css/product/feedback.css' %}">
<link rel="stylesheet" href="{% static 'css/index/new.css' %}">
<link rel="stylesheet" href="{% static 'css/index/popular.css' %}">
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}
<title>Tencho</title>
{% endblock %}

{% block content %}
        <div class="product-form">
            <div class="product-top">
                <img src="{{product.get_image_url}}" class="product-img" alt="{{product.name}}">
                <div class="info-block">
                    <h1 class="product-title">
                        {{product.name}}
                    </h1>
                    <p class="product-price">
                        {{product.cost}}
                    </p>
                    <p>Доступные размеры:</p>
                    <div class="sizes product-sizes">
                        {% for size in sizes %}
                            <button type="button" value="{{size.name}}" onclick="fillForm(this)" class="size-option" data-size="{{ size.id }}">{{ size.name }}</button>
                        {% endfor %}
                    </div>
                    <div class="order-block">
                        <form id="form_buying_product" class="" action="{% url 'orders:basket_add'%}">
                            {% csrf_token %}
                            <div class="number">
                                <div class="form-group">
                                <input type="number" class="form-control" name="number" id="number" placeholder="Количество">
                                </div>
                                
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="size" id="size" placeholder="Размер" readonly>
                                
                                </div>
                            
                            
                            {% if user.is_authenticated%}
                            <div class="form-group">
                            <button class="order-block-button btn-buy"
                            type="submit" id="submit_btn"
                                    data-product_id = "{{ product.id }}"
                                    data-name ="{{ product.name }}"
                                    data-cost ="{{ product.cost }}"
                                    data-category = "{{product.category}}"
                            > В корзину</button>
                            </div>
                            {% else%}
                            <a href="{% url 'users:login'%}">В корзину</a>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            <div class="product-about">
                <h1>Описание:</h1>
                <p class="product-item-about">{{product.description}}</p>
            </div>
        </div>
        <div class="same">
            <p class="new-title">Похожие товары</p>
            <div class="new-items">
                {% for another_product in similars_products%}
                {% if another_product.category == product.category and counter < 3 and another_product.name != product.name%}
                <div class="item">
                    <div class="item-content">
                    <span class="detailed" onclick="modalWindow(this)" data-name="{{another_product.name}}" data-cost="{{another_product.cost}}"  data-img="{{another_product.image}}" data-desc="{{another_product.description}}" data-category="{{another_product.category}}">Подробнее</span>
                    <img src="{{another_product.get_image_url}}" alt="{{another_product.name}}">
                    <div class="underline"></div>
                    <p class="item-title">{{another_product.name}}</p>
                    <a href="/product_detail/{{another_product.id}}" onclick="buy(this)" data-name="{{another_product.name}}" data-cost="{{another_product.cost}}"  data-img="{{another_product.image}}" data-desc="{{another_product.description}}" data-category="{{another_product.category}}">Купить</a>
                    </div>
                    </div>
                    
                    {% endif %}
                    
                {% endfor %}
                    
                <!--Здесь используется genproduct.js функция с out-->
            </div>
        </div>
        <div class="feedback">
            <div class="feedback-title">
                <p>Отзывы</p>
            </div>
            <div class="feedback-content">
                <div class="feedbacks">
                    <div class="feedback-item">
                        <div class="item-top">
                            <div class="avatar"></div>
                            <p>Николай</p>
                            <img src="{% static 'img/stars1.png' %}" alt="stars">
                        </div>
                        <div class="item-bot">
                            <p>Чай великолепный! Заказываю уже в 7ой раз, пьём всей семьёй. Очень всем рекомендуем.</p>
                        </div>
                    </div>
                    <div class="feedback-item">
                        <div class="item-top">
                            <div class="avatar"></div>
                            <p>Олег</p>
                            <img src="{% static 'img/stars2.png' %}" alt="stars">
                        </div>
                        <div class="item-bot">
                            <p>Чай необычный. Не думаю, что подойдет как чай на каждый день, но в целом неплохо.</p>
                        </div>
                    </div>

                    <div class="feedback-item">
                        <div class="item-top">
                            <div class="avatar"></div>
                            <p>Василий</p>
                            <img src="{% static 'img/stars3.png' %}" alt="stars">
                        </div>
                        <div class="item-bot">
                            <p>Слишком крепкий чай получается. Пить слишком тяжело.</p>
                        </div>
                    </div>

                    <div class="feedback-item">
                        <div class="item-top">
                            <div class="avatar"></div>
                            <p>Дмитрий</p>
                            <img src="{% static 'img/stars4.png' %}" alt="stars">
                        </div>
                        <div class="item-bot">
                            <p>Вообще не понравился. Отвратительный на вкус, может не моё. Но больше такой заказывать не
                                буду.</p>
                        </div>
                    </div>
                </div>
                <div class="feedback-form">
                    <div class="feedback-form-title">
                        <p>Оставьте свой отзыв</p>
                    </div>
                    <div class="form-items">
                        <label for="name">Имя:</label>
                        <input type="text" placeholder="Введите имя">
                        <label for="stars">Оценка:</label>
                        <div class="stars" id="stars">
                            <svg class="star" width="33" height="33" viewBox="0 0 33 33" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M16.5 3.23607L19.2534 11.7102L19.4779 12.4012H20.2045H29.1147L21.9062 17.6385L21.3184 18.0656L21.5429 18.7566L24.2963 27.2307L17.0878 21.9934L16.5 21.5664L15.9122 21.9934L8.70366 27.2307L11.4571 18.7566L11.6816 18.0656L11.0938 17.6385L3.88525 12.4012H12.7955H13.5221L13.7466 11.7102L16.5 3.23607Z"
                                    stroke="#5F9D9F" stroke-width="2" />
                            </svg>
                            <svg class="star" width="33" height="33" viewBox="0 0 33 33" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M16.5 3.23607L19.2534 11.7102L19.4779 12.4012H20.2045H29.1147L21.9062 17.6385L21.3184 18.0656L21.5429 18.7566L24.2963 27.2307L17.0878 21.9934L16.5 21.5664L15.9122 21.9934L8.70366 27.2307L11.4571 18.7566L11.6816 18.0656L11.0938 17.6385L3.88525 12.4012H12.7955H13.5221L13.7466 11.7102L16.5 3.23607Z"
                                    stroke="#5F9D9F" stroke-width="2" />
                            </svg>
                            <svg class="star" width="33" height="33" viewBox="0 0 33 33" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M16.5 3.23607L19.2534 11.7102L19.4779 12.4012H20.2045H29.1147L21.9062 17.6385L21.3184 18.0656L21.5429 18.7566L24.2963 27.2307L17.0878 21.9934L16.5 21.5664L15.9122 21.9934L8.70366 27.2307L11.4571 18.7566L11.6816 18.0656L11.0938 17.6385L3.88525 12.4012H12.7955H13.5221L13.7466 11.7102L16.5 3.23607Z"
                                    stroke="#5F9D9F" stroke-width="2" />
                            </svg>
                            <svg class="star" width="33" height="33" viewBox="0 0 33 33" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M16.5 3.23607L19.2534 11.7102L19.4779 12.4012H20.2045H29.1147L21.9062 17.6385L21.3184 18.0656L21.5429 18.7566L24.2963 27.2307L17.0878 21.9934L16.5 21.5664L15.9122 21.9934L8.70366 27.2307L11.4571 18.7566L11.6816 18.0656L11.0938 17.6385L3.88525 12.4012H12.7955H13.5221L13.7466 11.7102L16.5 3.23607Z"
                                    stroke="#5F9D9F" stroke-width="2" />
                            </svg>
                            <svg class="star" width="33" height="33" viewBox="0 0 33 33" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M16.5 3.23607L19.2534 11.7102L19.4779 12.4012H20.2045H29.1147L21.9062 17.6385L21.3184 18.0656L21.5429 18.7566L24.2963 27.2307L17.0878 21.9934L16.5 21.5664L15.9122 21.9934L8.70366 27.2307L11.4571 18.7566L11.6816 18.0656L11.0938 17.6385L3.88525 12.4012H12.7955H13.5221L13.7466 11.7102L16.5 3.23607Z"
                                    stroke="#5F9D9F" stroke-width="2" />
                            </svg>
                        </div>
                        <label for="message">Отзыв:</label>
                        <textarea placeholder="Введите отзыв" name="message" id="message" cols="30"
                            rows="10"></textarea>
                        <a href="#">Отправить</a>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
        
        {% block footer %}
        <div class="back-btn">
            <a href="#header">
                <img src="{% static 'img/arrow-up5.png' %}" alt="back-scroll">
            </a>
        </div>
        <div class="zoom-modal">
            <div class="modal-content">
                <!--zoom.js-->
                <div class="modal-item">
                    <div class="modal-item-content">
                        <img src="" class="modal-image" alt="tofu">
                    </div>
                </div>
                <div class="about">
                    <h1 class="modal-title"></h1>
                    <p class="modal-price"></p>
                    <p>Размеры:</p>
                    <div class="sizes">
                        {% for size in sizes %}
                        <div>{{size.name}}</div>
                        {% endfor %}
                    </div>
                    <p class="modal-item-about"></p>
                </div>
                <span class="close">X</span>
            </div>
        </div>
{% endblock %}
{% block js%}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/burger.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.js' %}"></script>
    <script src="{% static 'js/zoom.js' %}"></script>
    <script src="{% static 'js/stars.js' %}"></script>
    <script src="{% static 'js/itemscount.js' %}"></script>
    <!--<script src="{% static 'js/genproduct.js' %}"></script>-->
    <script src="{% static 'js/cart.js' %}"></script>
    {% endblock%}