tencho/orders/urls.py
from django.urls import path

from . import views
from .views import basket_add, basket_delete

app_name = 'orders'  

urlpatterns = [
    path('',views.cart, name='order'),
    #path('baskets/add/<int:product_id>/',, name='basket_add'),
    #api
    path('basket/add/',basket_add,name='basket_add'),
    path('basket/delete/',basket_delete,name="basket_delete")
    #path('',views.about, name='about'),
    #path('catalogue/',include('products.urls'), namespace='catalogue')
]

tencho/products/urls.py
#from django.contrib import admin
from django.urls import path

from products import views
from .views import ProductsAPIViewsCataloque
app_name = 'products'  

urlpatterns = [
    path('',views.catalogue, name='catalogue'),
    #path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
    #api
    #пока что наш путь для получения 
    # главное чтобы в пути было api/ дальше версия api api/v1 ну и добавляем немного контекста api/v1/productlist

    #path('',views.about, name='about'),
    #path('catalogue/',include('products.urls'), namespace='catalogue')
]

tencho/tencho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from products.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',index, name='index'),
    path('product_detail/<int:product_id>/', product_detail, name='product_detail'),
    path('catalogue/',include('products.urls', namespace='catalogue')),
    path('about/', about, name='about'),
    path('users/',include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    #api
    path('api/v1/productlist_index/', ProductsAPIViews.as_view()),
    path('api/v1/productlist_index_new/', ProductsAPIViewsNews.as_view()),
    path('product_detail/<int:id>/api/v1/productlist_in_one_category/', ProductsAPIViewsInOneCategory.as_view()),
    path('api/v1/productlist_in_catalogue/', ProductsAPIViewsCataloque.as_view()),
    
] \
+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tencho/users/urls.py
#from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'users'  

urlpatterns = [
    path('cabinet/',views.cabinet, name='cabinet'),
    path('cabinet_no_autorization/',views.cabinet_no_autorization, name='cabinet_no_autorization'),
    path('cabinet/data/',views.data, name='data'),
    path('cabinet/delivery/', views.delivery, name='delivery'),
    path('cabinet/users_cards/',views.users_cards, name='users_cards'),
    path('cabinet/purchases/', views.purchases, name = 'purchases'),
    path('cabinet/favorite/', views.favorite, name='favorite'),
    path('cabinet/notifications',views.notify, name='notify'),
    path('login/', views.login,name='login'),
    path('registation/', views.registration, name='registration'),
    path('logout/', views.logout_view, name='logout'),
]

tencho/products/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class CategoryProducts(models.Model):
    name=models.CharField(max_length=128,unique=True)
    code=models.CharField(max_length=128, default='empty')

    class Meta: 
        verbose_name='Категория'
        verbose_name_plural='Категории'
    
    def __str__(self):
        return self.name
    
class Size(models.Model):
    name=models.CharField(max_length=12)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'
    
class Product(models.Model):
    #ВНИМАНИЕ on_delete указывает, что произойдет, если поле КАТЕГОРИЯ будет удалено
    name=models.CharField(max_length=128)
    cost=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(CategoryProducts,on_delete=models.CASCADE)#тоже будет удален
    description=models.TextField()
    image=models.ImageField(upload_to='products_images/')
    is_active=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True, auto_now=False)
    updated=models.DateTimeField(auto_now_add=False, auto_now=True)

    def get_image_url(self):
           """Возвращает полный URL изображения с учетом MEDIA_URL."""
           if self.image:
               return f"{settings.MEDIA_URL}{self.image.name}"
           return None

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
    
    def __str__(self):
        return '%s %s' % (self.category, self.name)

tencho/products/views.py
from rest_framework import generics
from .models import Product, Size
from orders.models import Basket
from users.models import User
from .serializers import *
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import render, get_object_or_404
import requests

# Create your views here.
#отображение страниц
def index(request):
    response = requests.get('http://127.0.0.1:8001/api/v1/productlist_index/')
    if response.status_code == 200:  # Проверяем, был ли запрос успешным
        popular_products = response.json()  # Получаем данные в формате JSON
    else:
        popular_products = []  # Возвращаем пустой список, если запрос не удался
    
    response = requests.get('http://127.0.0.1:8001/api/v1/productlist_index_new/')
    if response.status_code == 200:  # Проверяем, был ли запрос успешным
        new_products = response.json()  # Получаем данные в формате JSON
    else:
        new_products = []  # Возвращаем пустой список, если запрос не удался
    #popular_products = 'api/v1/productlist_index/'
    context = {
        'sizes': Size.objects.all(),
        'popular_products':popular_products,
        'new_products': new_products
    }
    return render(request,'products/index.html', context)

def catalogue(request):
    response = requests.get('http://127.0.0.1:8001/api/v1/productlist_in_catalogue/')
    if response.status_code == 200:  # Проверяем, был ли запрос успешным
        all_products = response.json()  # Получаем данные в формате JSON
    else:
        all_products = []  # Возвращаем пустой список, если запрос не удался
    
    context = {
        'sizes': Size.objects.all(),
        'all_products': all_products
    }
    return render(request, 'products/catalogue.html', context)


def about(request):
    return render(request,'about.html')

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    similars_products = Product.objects.filter(category=product.category).exclude(pk=product.pk)[:3]  # похожие товары

    context = {
        'sizes': Size.objects.all(),
        'product': product,
        'similars_products': similars_products,
        'counter': 0
    }
    return render(request, 'products/product.html', context)

#Обработчики событий
# def basket_add(request, product_id):
#     if not request.user.is_authenticated:
#         # Сохранение URL в сессии
#         request.session['next_url'] = request.META.get('HTTP_REFERER', '/') 

#         return redirect('users:login')
    

#APIViews
class ProductsAPIViews(APIView):# в общем это то, что мы получаем
    def get(self, request):
        all_products = Product.objects.order_by('created')[:12]
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    
class ProductsAPIViewsInOneCategory(APIView):# в общем это то, что мы получаем
    def get(self, request, id):
        all_products = Product.objects.all()
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    
class ProductsAPIViewsNews(APIView):# в общем это то, что мы получаем
    def get(self, request):
        all_products = Product.objects.order_by('-created')[:6]
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    
class ProductsAPIViewsCataloque(APIView):# в общем это то, что мы получаем
    def get(self, request):
        all_products = Product.objects.all()
        serialized_products = ProductSerializer(all_products, many=True)
        return Response(serialized_products.data)
    



# А МОЖНО И ВОТ ТАК

# class ProductsAPIViews(APIView):# он уже говорит какой запрос пришел, а функции мы прописали сами
#     def get(self, request):
#         all_products = Product.objects.all()
#         serialized_products = ProductSerializer(all_products, many=True).data
        
#         response_data = {} 
#         for i, product in enumerate(serialized_products):
#             response_data[str(i + 1)] = product 
        
#         return Response(response_data)
    
#     def post(self, request):
#         serializer  =ProductSerializer(data=request.data)
#         serializer.is_valid(reise_exception=True)
#         serializer.save()
#         return Response({serializer.data})


#МОЖНО ТАК
# class ProductsAPIViews(generics.ListAPIView):# это у нас представление
#     queryset=Product.objects.all()# считываем все
#     serializer_class = ProductSerializer# сериализатор наш

tencho/products/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/about/about.css' %}">
{% endblock %}

{% block title %}
<title>Tencho - About</title>
{% endblock %}

{% block content %}
        <div class="about-tencho">
            <img src="{% static 'img/aboutlogo.png' %}" alt="logo">
            <p>Тенчо - имя японской эпохи. После эпохи Конина и до эпохи Дзивы. Этот период охватывал годы с января 824 по январь 834 года. Правящим императорам был Дзюнна-тэнно. Тенчо ганнэн 6 февраля 824 года: Название новой эры было создано для обозначения события или серии событий. Предыдущая эра закончилась, и новая началась в Конине 15, в 5-й день 1-го месяца 824 года.</p>
            <p>Все продукты в<span> TENCHO </span>мы привозим прямиком из Японии. Все наши продукты имеют высокую планку качества и проходят множество различных проверок перед тем, как попасть в руки к покупателю.</p>
        </div>
        {% endblock %}
       {% block js %}
       <script src="{% static 'js/burger.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.js' %}"></script>
    {%endblock%}

tencho/products/templates/base.html
{% load static %}

<style>
    @font-face {
        font-family: Montserrat;
        src: url({% static 'fonts/Montserrat.ttf'%});
    }
    
    @font-face {
        font-family: MontserratBold;
        src: url({% static 'fonts/Montserrat.ttf'%});
        font-weight: 900;
    }
    
    @font-face {
        font-family: MontserratSemiBold;
        src: url({% static 'fonts/Montserrat.ttf'%});
        font-weight: 700;
    }
    
    @font-face {
        font-family: Montserrat300;
        src: url({% static 'fonts/Montserrat.ttf'%});
        font-weight: 300;
    }
    
    @font-face {
        font-family: MontserratExtraLight;
        src: url({% static 'fonts/Montserrat.ttf'%});
        font-weight: 200;
    }
    

</style>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/zoom.css' %}">
    {% block css %} {% endblock %}
    {% block title %} {% endblock %}
</head>

<body>
    
    <div class="wrap" style = "background-image: url({% static 'img/wavesbg.png' %});">
        <div class="header" id="header">
            <div class="logo">
                <a href="{% url 'index' %}"><img src="{% static 'img/tenchohyrogliphslogo.png'%}" alt="logo"></a>
            </div>
            <div class="menu">
                <!-- Настроить якоря в конце -->
                <a href="{% url 'about'%}">О компании</a>
                <div class="submenu-point">
                    <a href="{% url 'catalogue:catalogue'%}" class="submenu-point">Каталог </a>
                    <div class="submenu">
                        <a href="#">Рыба</a>
                        <a href="#">Чай</a>
                        <a href="#">Соусы</a>
                        <a href="#">Рис</a>
                        <a href="#">Специи</a>
                    </div>
                </div>
                {% if user.is_authenticated%}
                <a href="{% url 'users:cabinet'%}">Кабинет</a>
                {% else %}
                <a href="{% url 'users:cabinet_no_autorization'%}">Кабинет</a>
                {% endif %}
                <a href="#contacts">Контакты</a>
                <a href="{% url 'users:login'%}" class="hided-menu">Войти</a>
                {% if user.is_authenticated%}
                <a href="{% url 'orders:order'%}" class="hided-menu">Корзина</a>
                {% endif %}
            </div>
            <div class="icons">
                <a href="{% url 'users:login'%}">
                    <svg width="41" height="40" class="login" viewBox="0 0 41 40" fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                            d="M33.1332 27.8499L33.5332 29.7499C33.9122 31.3926 33.538 33.1187 32.5126 34.4568C31.4872 35.795 29.9179 36.6053 28.2332 36.6666H12.7665C11.0818 36.6053 9.51245 35.795 8.48708 34.4568C7.46171 33.1187 7.08744 31.3926 7.4665 29.7499L7.8665 27.8499C8.32656 25.2779 10.5375 23.3877 13.1498 23.3333H27.8498C30.4621 23.3877 32.6731 25.2779 33.1332 27.8499ZM28.2332 34.1499C29.0795 34.1401 29.8759 33.748 30.3998 33.0833V33.0999C31.0426 32.2936 31.2931 31.2429 31.0832 30.2333L30.6832 28.3333C30.4612 26.9252 29.2742 25.8709 27.8498 25.8166H13.1498C11.7254 25.8709 10.5384 26.9252 10.3165 28.3333L9.9165 30.2333C9.71176 31.2376 9.96194 32.281 10.5998 33.0833C11.1237 33.748 11.9202 34.1401 12.7665 34.1499H28.2332Z"
                            fill="#5F9D9F" />
                        <path fill-rule="evenodd" clip-rule="evenodd"
                            d="M21.3334 20H19.6667C15.9848 20 13 17.0152 13 13.3333V8.93329C12.9956 7.44672 13.5842 6.01976 14.6353 4.96859C15.6865 3.91742 17.1135 3.32885 18.6 3.33329H22.4C23.8866 3.32885 25.3136 3.91742 26.3647 4.96859C27.4159 6.01976 28.0045 7.44672 28 8.93329V13.3333C28 17.0152 25.0153 20 21.3334 20ZM18.6 5.8333C16.888 5.8333 15.5 7.22122 15.5 8.9333V13.3333C15.5 15.6345 17.3655 17.5 19.6667 17.5H21.3334C23.6346 17.5 25.5 15.6345 25.5 13.3333V8.9333C25.5 8.11113 25.1734 7.32263 24.5921 6.74127C24.0107 6.15991 23.2222 5.8333 22.4 5.8333H18.6Z"
                            fill="#5F9D9F" />
                    </svg>
                </a>
                {% if user.is_authenticated%}
                <a href="{% url 'orders:order'%}">
                    <svg class="cart" width="41" height="40" viewBox="0 0 41 40" fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                            d="M6.2832 7.08337H7.94987L8.0332 7.10004C10.3435 7.14485 12.3621 8.67228 13.0332 10.8834L13.3665 12.0334H30.7499C32.2849 12.0404 33.7425 12.7084 34.7499 13.8667C35.7544 15.0323 36.1989 16.579 35.9665 18.1L34.9665 25C34.6335 27.6449 32.3988 29.6376 29.7332 29.6667H19.9332C17.592 29.658 15.5303 28.1235 14.8499 25.8834L10.6332 11.6667C10.3103 10.447 9.21154 9.59393 7.94987 9.58337H6.2832C5.59285 9.58337 5.0332 9.02373 5.0332 8.33337C5.0332 7.64302 5.59285 7.08337 6.2832 7.08337ZM17.2499 25.0834C17.6037 26.27 18.6949 27.0834 19.9332 27.0834H29.7332C31.1127 27.0684 32.2808 26.0621 32.4999 24.7L33.4999 17.7834C33.6361 16.9783 33.414 16.1538 32.8919 15.526C32.3698 14.8982 31.5996 14.5296 30.7832 14.5167H14.1165L17.2499 25.0834Z"
                            fill="#5F9D9F" />
                        <path
                            d="M19.55 31.6667C18.6295 31.6667 17.8833 32.4129 17.8833 33.3334C17.8833 34.2539 18.6295 35.0001 19.55 35.0001C20.4704 35.0001 21.2166 34.2539 21.2166 33.3334C21.2166 32.4129 20.4704 31.6667 19.55 31.6667Z"
                            fill="#5F9D9F" />
                        <path
                            d="M29.55 31.6667C28.6295 31.6667 27.8833 32.4129 27.8833 33.3334C27.8833 34.2539 28.6295 35.0001 29.55 35.0001C30.4704 35.0001 31.2166 34.2539 31.2166 33.3334C31.2166 32.4129 30.4704 31.6667 29.55 31.6667Z"
                            fill="#5F9D9F" />
                    </svg>
                </a>
                {% endif %}
            </div>
            <div class="burger">
                <span></span>
            </div>
        </div>

        {% block content %} {%endblock%}

        

        <div class="footer">
            <div class="logo">
                <img src="{% static 'img/footer-logo.png' %}" alt="footer-logo">
            </div>
            <div class="contacts" id="contacts">
                <p>Адрес: Улица Пушкина, 12</p>
                <p>Email: tencho@group.ru</p>
                <p>Телефон: 7 (962) 260 61 57</p>
            </div>
            <div class="socials">
                <p>Мы в соц. сетях:</p>
                <div class="social-icons">
                    <svg class="youtube" width="49" height="48" viewBox="0 0 49 48" fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <g clip-path="url(#clip0_36_496)">
                            <path class="bg"
                                d="M47.5442 12.3708C47.2728 11.3496 46.738 10.4177 45.9933 9.66813C45.2485 8.9186 44.32 8.37782 43.3006 8.09991C39.5479 7.09082 24.5479 7.09082 24.5479 7.09082C24.5479 7.09082 9.54785 7.09082 5.79512 8.09991C4.77571 8.37782 3.84717 8.9186 3.10243 9.66813C2.35768 10.4177 1.82286 11.3496 1.55149 12.3708C0.547852 16.1399 0.547852 23.9999 0.547852 23.9999C0.547852 23.9999 0.547852 31.8599 1.55149 35.629C1.82286 36.6502 2.35768 37.5822 3.10243 38.3317C3.84717 39.0812 4.77571 39.622 5.79512 39.8999C9.54785 40.909 24.5479 40.909 24.5479 40.909C24.5479 40.909 39.5479 40.909 43.3006 39.8999C44.32 39.622 45.2485 39.0812 45.9933 38.3317C46.738 37.5822 47.2728 36.6502 47.5442 35.629C48.5479 31.8599 48.5479 23.9999 48.5479 23.9999C48.5479 23.9999 48.5479 16.1399 47.5442 12.3708Z"
                                fill="#5F9D9F" />
                            <path d="M19.6387 31.1373V16.8628L32.1841 24.0001L19.6387 31.1373Z" fill="#FEFEFE" />
                        </g>
                        <defs>
                            <clipPath id="clip0_36_496">
                                <rect width="48" height="48" fill="white" transform="translate(0.5)" />
                            </clipPath>
                        </defs>
                    </svg>
                    <svg class="facebook" width="49" height="48" viewBox="0 0 49 48" fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <g clip-path="url(#clip0_36_491)">
                            <path class="bg"
                                d="M48.5 24C48.5 10.7452 37.7548 0 24.5 0C11.2452 0 0.5 10.7452 0.5 24C0.5 35.9789 9.27641 45.908 20.75 47.7084V30.9375H14.6562V24H20.75V18.7125C20.75 12.6975 24.3331 9.375 29.8152 9.375C32.4402 9.375 35.1875 9.84375 35.1875 9.84375V15.75H32.1613C29.18 15.75 28.25 17.6002 28.25 19.5V24H34.9062L33.8422 30.9375H28.25V47.7084C39.7236 45.908 48.5 35.9789 48.5 24Z"
                                fill="#5F9D9F" />
                            <path
                                d="M33.8422 30.9375L34.9062 24H28.25V19.5C28.25 17.602 29.18 15.75 32.1613 15.75H35.1875V9.84375C35.1875 9.84375 32.4411 9.375 29.8152 9.375C24.3331 9.375 20.75 12.6975 20.75 18.7125V24H14.6562V30.9375H20.75V47.7084C23.2349 48.0972 25.7651 48.0972 28.25 47.7084V30.9375H33.8422Z"
                                fill="white" />
                        </g>
                        <defs>
                            <clipPath id="clip0_36_491">
                                <rect width="48" height="48" fill="white" transform="translate(0.5)" />
                            </clipPath>
                        </defs>
                    </svg>
                    <svg class="twitter" width="48" height="48" viewBox="0 0 49 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g clip-path="url(#clip0_36_494)">
                            <path class="bg"
                                d="M15.595 43.5015C33.7083 43.5015 43.6155 28.4948 43.6155 15.481C43.6155 15.0548 43.6155 14.6305 43.5867 14.2081C45.5141 12.814 47.1778 11.0878 48.5 9.11048C46.7028 9.90728 44.7961 10.4296 42.8437 10.6599C44.8996 9.4293 46.4383 7.49349 47.1733 5.21288C45.2402 6.3601 43.1253 7.16853 40.9198 7.60328C39.435 6.02443 37.4712 4.97896 35.3324 4.62865C33.1935 4.27834 30.9988 4.64271 29.0879 5.66539C27.177 6.68806 25.6564 8.31203 24.7615 10.286C23.8665 12.2599 23.6471 14.4738 24.1371 16.585C20.2218 16.3886 16.3915 15.3711 12.8949 13.5985C9.39831 11.8259 6.31353 9.3378 3.8408 6.29576C2.58146 8.46375 2.19574 11.0302 2.7622 13.4726C3.32865 15.915 4.80468 18.0497 6.88976 19.442C5.32246 19.3961 3.7893 18.9733 2.42 18.2094V18.3342C2.42062 20.6079 3.2077 22.8114 4.64774 24.5709C6.08778 26.3304 8.09212 27.5377 10.3208 27.9879C8.87096 28.3834 7.34975 28.4412 5.87408 28.1569C6.50363 30.1135 7.72886 31.8246 9.37848 33.0508C11.0281 34.277 13.0197 34.957 15.0747 34.9959C13.0329 36.6009 10.6946 37.7875 8.19375 38.4879C5.69287 39.1883 3.07843 39.3888 0.5 39.0778C5.00367 41.9679 10.2438 43.5009 15.595 43.4938"
                                fill="#5F9D9F" />
                        </g>
                        <defs>
                            <clipPath id="clip0_36_494">
                                <rect width="48" height="48" fill="white" transform="translate(0.5)" />
                            </clipPath>
                        </defs>
                    </svg>
                </div>
            </div>
        </div>
        {% block footer %} {%endblock%}
    </div>
    {% block js %} {%endblock%}
    
</body>

</html>